### ISSUE TITLE
No output on query

### ISSUE THREAD

**Issue by wiggins-philip** [jsumners/alfred-emoji#101] opened 2023-03-08 18:20 UTC
No results showing in alfred. I'm not sure if this is an issue with flow or with alfred. Debugging shows output, but not Alfred.
<img width="1469" alt="Screenshot 2023-03-08 at 12 18 47 PM" src="https://user-images.githubusercontent.com/46609301/223798377-97d29e75-fb94-4bed-8323-16903bdd8ccf.png">

**Comment by jsumners** [comment] 2023-03-08 20:29
Duplicate of https://github.com/jsumners/alfred-emoji/issues/100.

It seems to be some issue with Alfred that just "clears up" after a while. If you're able to find a root cause, that'd be fantastic. But I can't reproduce this locally, even though it _has_ happened to me in the past, and have not seen any indication it is a problem with the workflow.

**Closed by jsumners** 2023-03-08 20:29 UTC
