### ISSUE TITLE
Some emijies are not avaliable

### ISSUE THREAD

**Issue by kuncevic** [jsumners/alfred-emoji#58] opened 2021-05-21 05:10 UTC
For example diving mask is not there https://emojipedia.org/diving-mask as well as a bunch of other emogies.

<img width="289" alt="image" src="https://user-images.githubusercontent.com/1283734/119085207-a4c84f00-ba46-11eb-90d7-8c9dbcf873cd.png">

Any plans to get them included at some point soon?

**Comment by jsumners** [comment] 2021-05-21 11:58
This is basically a duplicate of https://github.com/jsumners/alfred-emoji/issues/35.

> Any plans to get them included at some point soon?

Please read my introduction on https://github.com/jsumners .

As for what needs to be done, we need to update to the latest `emojilib` dependency and rebuild on the latest macOS.

**Closed by jsumners** 2021-05-21 11:58 UTC
Labels: duplicate
